nsp-ads-core|nsp-ads-core|com.nsp.ads.core|master|https://github.com/niksan-dev/nsp-ads-core.git|
nsp-ads-admob|nsp-ads-admob|com.nsp.ads.admob|master|https://github.com/niksan-dev/nsp-ads-admob.git|nsp-ads-core
nsp-ads-unity|nsp-ads-unity|com.nsp.ads.unity|master|https://github.com/niksan-dev/nsp-ads-unity.git|nsp-ads-core
nsp-ui|nsp-ui|com.nsp.ui|master|https://github.com/niksan-dev/nsp-ui.git|
nsp-analytics|nsp-analytics|com.nsp.analytics|master|https://github.com/niksan-dev/nsp-analytics.git|
nsp-leaderboard|nsp-leaderboard|com.nsp-leaderboard|master|https://github.com/niksan-dev/nsp-leaderboard.git|
nsp-iap|nsp-iap|com.nsp-iap|master|https://github.com/niksan-dev/nsp-iap.git|
